#server:
#  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cxx_blog?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password:
  redis:
      host: localhost
      timeout: 5000
  mail:
      host:  smtp.163.com
      username: skymomail@163.com
      password: your
      default-encoding: UTF-8
  jackson:
      time-zone: GMT+8
      date-format: yyyy-MM-dd HH:mm:ss

fanli:
  jwt:
    # 部署上线务必修改此配置，以保证token的安全性
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 172800
    header: token
